Repository zrock-dev/antwood, pull requests merged in 2023-11, with the labels that each got.

#24 QA Deployment workflow migration
  .github/disabled_workflows/qa_env_deployment_workflow.yml
Labels: question, ticket

#30 Search bar - PR for Testing
  backend/product_management/app/config/Server.go
  backend/product_management/context/controllers/responses/SearchResponder.go
  backend/product_management/router/SearchRouter.go
  backend/product_management/router/SneakerRouter.go
  frontend/src/app/admin/search/[input]/page.jsx
  frontend/src/app/products/search/[input]/page.jsx
  frontend/src/components/admin/navbar/AdminNavbar.jsx
  frontend/src/components/admin/products/AdminGallery.jsx
  frontend/src/components/admin/products/AdminProductCard.jsx
  frontend/src/components/admin/products/AdminSearchGallery.jsx
  frontend/src/components/navbar/Navbar.jsx
  frontend/src/components/products/NoProductsFound.jsx
  frontend/src/components/products/ProductCard.jsx
  frontend/src/components/products/ProductRenderer.jsx
  frontend/src/components/products/product_renderers/DefaultProducts.jsx
  frontend/src/components/products/product_renderers/ProductSearch.jsx
  frontend/src/components/search/SearchSuggestion.jsx
  frontend/src/components/search/Searcher.jsx
  frontend/src/icons/SearchIcon.jsx
  frontend/src/requests/SneakersRequest.js
  frontend/src/styles/elemens/customizable.css
  frontend/src/styles/navbar/navbar.css
  frontend/src/styles/products/noResults.css
  frontend/src/styles/search/search.css
Labels: deployment

#35 fix: bug fixed when trying to search using special characters
  frontend/src/components/product/ProductDetails.jsx
  frontend/src/components/search/Searcher.jsx
  frontend/src/styles/elemens/customizable.css
  frontend/src/styles/product/product_details.css
Labels: bug

#40 Deployment | [US-10], [TK-02]
  backend/product_management/app/config/Server.go
  backend/product_management/app/models/Sneaker.go
  backend/product_management/app/models/SneakerJoined.go
  backend/product_management/app/repository/CloaudinaryRepository.go
  backend/product_management/app/repository/ReviewRepository.go
  backend/product_management/app/repository/SneakerColorRepository.go
  backend/product_management/app/repository/SneakerRepository.go
  backend/product_management/context/controllers/requests/CloudinaryRequester.go
  backend/product_management/context/controllers/requests/Parser.go
  backend/product_management/context/controllers/requests/ReviewRequester.go
  backend/product_management/context/controllers/requests/SneakerColorRequester.go
  backend/product_management/context/controllers/requests/SneakerRequester.go
  backend/product_management/context/controllers/responses/SneakerColorResponder.go
  backend/product_management/context/controllers/responses/SneakerResponder.go
  backend/product_management/router/CloudinaryRouter.go
  backend/product_management/router/SneakerColorRouter.go
  backend/product_management/router/SneakerRouter.go
  frontend/src/app/admin/product/[id]/page.jsx
  frontend/src/app/admin/product/page.jsx
  frontend/src/components/admin-panel/AdminPanelColorsForm.jsx
  frontend/src/components/admin-panel/AdminPanelRenderer.jsx
  frontend/src/components/admin-panel/AdmnPanelForm.jsx
  frontend/src/components/admin-panel/ColorPicker.jsx
  frontend/src/components/admin-panel/ImageSelector.jsx
  frontend/src/components/admin-panel/SizeSelectorForm.jsx
  frontend/src/components/admin-panel/TagSelector.jsx
  frontend/src/components/admin/confirmations/DeleteSneakerColorConfirmation.jsx
  frontend/src/components/admin/confirmations/DeleteSneakerConfirmation.jsx
  frontend/src/components/admin/products/AdminProductCard.jsx
  frontend/src/components/cart/CartRenderer.jsx
  frontend/src/components/product/SingleProductRenderer.jsx
  frontend/src/components/reviews/ProductReview.jsx
  frontend/src/components/reviews/ReviewForm.jsx
  frontend/src/context/CartContext.js
  frontend/src/requests/SneakersRequest.js
  frontend/src/styles/admin_panel/admin_panel.css
  frontend/src/styles/admin_panel/admin_panel_colors_form.css
  frontend/src/styles/admin_panel/admin_panel_form.css
  frontend/src/styles/admin_panel/admin_panel_sizes.css
  frontend/src/styles/admin_panel/color_picker.module.css
  frontend/src/styles/admin_panel/tag_selector.css
  frontend/src/styles/globals.css
  frontend/src/utils/ImageFormUtils.js
  frontend/src/utils/Packer.js
  frontend/src/utils/SneakerFormValidation.js
  frontend/src/utils/Suggestions.js
  frontend/src/utils/color-picker.js
  solestyle-dev.yml
  solestyle-prod.yml
  utils/nginx/swagger.conf
  utils/swagger/swagger.json
Labels: deployment

#45 Filters
  backend/product_management/app/config/Server.go
  backend/product_management/context/controllers/responses/FilterResponde.go
  backend/product_management/context/controllers/responses/SearchResponder.go
  backend/product_management/context/controllers/responses/SneakerResponder.go
  backend/product_management/router/FilterRouter.go
  backend/product_management/router/SneakerRouter.go
  frontend/package-lock.json
  frontend/package.json
  frontend/src/app/products/filter/page.jsx
  frontend/src/components/Section.jsx
  frontend/src/components/filters/FilterRenderer.jsx
  frontend/src/components/filters/sections/BrandSection.jsx
  frontend/src/components/filters/sections/ColorSection.jsx
  frontend/src/components/filters/sections/OthersSection.jsx
  frontend/src/components/filters/sections/PriceSection.jsx
  frontend/src/components/filters/sections/SizeSection.jsx
  frontend/src/components/layouts/Layout.jsx
  frontend/src/components/navbar/Navbar.jsx
  frontend/src/components/product/ProductDetails.jsx
  frontend/src/components/products/ProductRenderer.jsx
  frontend/src/components/products/product_renderers/DefaultProducts.jsx
  frontend/src/components/products/product_renderers/ProductFilter.jsx
  frontend/src/components/products/product_renderers/ProductSearch.jsx
  frontend/src/components/products/product_renderers/ProductSuggestions.jsx
  frontend/src/components/search/Searcher.jsx
  frontend/src/context/ProductResultsContext.js
  frontend/src/icons/Minus.jsx
  frontend/src/requests/SneakersRequest.js
  frontend/src/styles/elemens/customizable.css
  frontend/src/styles/elemens/general.css
  frontend/src/styles/filters/filterColor.css
  frontend/src/styles/filters/filterText.css
  frontend/src/styles/filters/filters.css
  frontend/src/styles/landing_page/page.css
  frontend/src/styles/navbar/navbar.css
  frontend/src/styles/products/products.css
Labels: deployment

#52 [US-15], [US-19] Deployment Request
  backend/account_management/Dockerfile.debug
  backend/account_management/context/controllers/AuthController.go
  backend/account_management/context/service/AuthProvider.go
  backend/account_management/context/service/authentication_providers/CustomErrors.go
  backend/account_management/context/service/authentication_providers/Google.go
  backend/account_management/context/service/authentication_providers/ProvidersBase.go
  backend/account_management/context/service/authentication_providers/SoleStyle.go
  backend/account_management/context/service/authentication_providers/Utils.go
  backend/account_management/context/service/authentication_providers/Validations.go
  backend/account_management/go.mod
  backend/account_management/go.sum
  backend/account_management/routes/routes.go
  backend/shoppingCardManagement/app/models/ShoppingCard.go
  backend/shoppingCardManagement/app/repository/OrderRepository.go
  backend/shoppingCardManagement/app/repository/UnpaidOrderRepository.go
  backend/shoppingCardManagement/context/controllers/orders/OrderController.go
  backend/shoppingCardManagement/router/routes.go
  frontend/src/app/profile/layout.jsx
  frontend/src/app/profile/order/page.jsx
  frontend/src/components/PaymentMessage.jsx
  frontend/src/components/auth/AuthFormWrapper.jsx
  frontend/src/components/auth/GoogleSignInButton.jsx
  frontend/src/components/order/OrderRenderer.jsx
  frontend/src/components/order/Pagination.jsx
  frontend/src/components/order/ReceipModalRenderer.jsx
  frontend/src/components/profile/ProfileRenderer.jsx
  frontend/src/components/reviews/ReviewForm.jsx
  frontend/src/requests/OrderRequest.js
  frontend/src/styles/order/order.css
  frontend/src/styles/order/receipt_modal.css
  frontend/src/styles/profile/profile.css
  frontend/src/utils/Parser.js
  solestyle-debug.yml
Labels: deployment

#55 Landing page
  frontend/src/app/page.jsx
  frontend/src/components/landing_page/Collections.jsx
  frontend/src/components/landing_page/Footer.jsx
  frontend/src/components/landing_page/FrontPage.jsx
  frontend/src/components/layouts/NormalLayout.jsx
  frontend/src/components/navbar/Navbar.jsx
  frontend/src/components/products/product_renderers/DefaultProducts.jsx
  frontend/src/components/products/product_renderers/ProductFilter.jsx
  frontend/src/components/products/product_renderers/ProductSearch.jsx
  frontend/src/components/profile/ProfileRenderer.jsx
  frontend/src/icons/Footer/Facebook.jsx
  frontend/src/icons/Footer/Instagram.jsx
  frontend/src/icons/Footer/Pointer.jsx
  frontend/src/icons/Footer/Twitter.jsx
  frontend/src/icons/Footer/Youtube.jsx
  frontend/src/icons/RightFromBracket.jsx
  frontend/src/icons/UserIcon.jsx
  frontend/src/styles/elemens/customizable.css
  frontend/src/styles/elemens/general.css
  frontend/src/styles/filters/filters.css
  frontend/src/styles/footer/footer.css
  frontend/src/styles/landing_page/collections.css
  frontend/src/styles/landing_page/footer.css
  frontend/src/styles/landing_page/frontPage.css
  frontend/src/styles/navbar/navbar.css
  frontend/src/styles/profile/profile.css
Labels: deployment
